---
title: "DatabaseRepair"
author: "Alan Jackson"
date: "3/14/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

##  delete and save last days data


```{r del}

path <- "/home/ajackson/Dropbox/Rprojects/Covid/"

foo <- readRDS("/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")

#indicies <- tail(which(foo$County=="Total"),2)

#foo <- foo[1:indicies[1],]
#foo <- foo[1:71,]

foo <- foo[1:1040,]

# Save an accumulated file in case of a failure
#saveRDS(foo,paste0("/home/ajackson/Dropbox/Rprojects/Covid/",lubridate::today(),"_Covid.rds"))
# Save the real file for later use
saveRDS(foo,"/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")
# Also save to mirror site
saveRDS(foo,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Covid.rds")

#############   tests
foo <- readRDS("/home/ajackson/Dropbox/Rprojects/Covid/Testing.rds")
foo <- foo[1:11,]

# Save the real file for later use
saveRDS(foo,"/home/ajackson/Dropbox/Rprojects/Covid/Testing.rds")
# Also save to mirror site
saveRDS(foo,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Testing.rds")

#############   deaths
foo <- readRDS("/home/ajackson/Dropbox/Rprojects/Covid/Deaths.rds")

foo <- foo[1:10,]

# Save the real file for later use
saveRDS(foo,"/home/ajackson/Dropbox/Rprojects/Covid/Deaths.rds")
# Also save to mirror site
saveRDS(foo,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Deaths.rds")



```

##  Delete Total field

```{r delete total}

path <- "/home/ajackson/Dropbox/Rprojects/Covid/"

foo <- readRDS("/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")

foo <- foo %>% filter(County!="Total")

# Save an accumulated file in case of a failure
saveRDS(foo,paste0("/home/ajackson/Dropbox/Rprojects/Covid/",lubridate::today(),"_Covid.rds"))
# Save the real file for later use
saveRDS(foo,"/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")
# Also save to mirror site
saveRDS(foo,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Covid.rds")



```

##  Add Deaths field

```{r delete total}

path <- "/home/ajackson/Dropbox/Rprojects/Covid/"

foo <- readRDS("/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")

foo <- foo %>% mutate(Deaths="-")

# Save an accumulated file in case of a failure
saveRDS(foo,paste0("/home/ajackson/Dropbox/Rprojects/Covid/",lubridate::today(),"_Covid.rds"))
# Save the real file for later use
saveRDS(foo,"/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")
# Also save to mirror site
saveRDS(foo,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Covid.rds")



```

##  Fix Covid

```{r deathdata}

path <- "/home/ajackson/Dropbox/Rprojects/Covid/"

foo <- readRDS("/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")

foo <- slice(foo,-1295:-1548)

saveRDS(foo ,paste0("/home/ajackson/Dropbox/Rprojects/Covid/",lubridate::today(),"_deaths.rds"))
# Save the real file for later use
saveRDS(foo,"/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")
# Also save to mirror site
saveRDS(foo,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Covid.rds")
```

##  Add LastUpdate field

```{r deathdata}

path <- "/home/ajackson/Dropbox/Rprojects/Covid/"

foo <- readRDS("/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")

foo <- foo %>% 
  mutate(LastUpdate=Date) %>% 
  mutate(Deaths=str_replace(Deaths,"-", "na")) %>% 
  mutate(Deaths=as.numeric(Deaths)) %>% 
  replace_na(list(Count_ = 0, Deaths=0))

hour(foo$LastUpdate) <- 11

foo$LastUpdate <- as.character(foo$LastUpdate)


# Save the real file for later use
saveRDS(foo,"/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")
# Also save to mirror site
saveRDS(foo,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Covid.rds")
```

## Subtract one day from dates - I have retrieval date, not actual date

```{r shift dates}

path <- "/home/ajackson/Dropbox/Rprojects/Covid/"

foo <- readRDS("/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")
foo <- foo %>% 
  mutate(Date=Date-1)
# Save the real file for later use
saveRDS(foo,"/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")
# Also save to mirror site
saveRDS(foo,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Covid.rds")

#    deaths
foo <- readRDS("/home/ajackson/Dropbox/Rprojects/Covid/Deaths.rds")

foo <- foo %>% 
  mutate(Date=if_else(Date>ymd("2020-03-22"),Date-1, Date))

# Save the real file for later use
saveRDS(foo,"/home/ajackson/Dropbox/Rprojects/Covid/Deaths.rds")
# Also save to mirror site
saveRDS(foo,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Deaths.rds")

# Tests
foo <- readRDS("/home/ajackson/Dropbox/Rprojects/Covid/Testing.rds")
foo <- foo %>% 
  mutate(Date=Date-1)

# Save the real file for later use
saveRDS(foo,"/home/ajackson/Dropbox/Rprojects/Covid/Testing.rds")
# Also save to mirror site
saveRDS(foo,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Testing.rds")

```


## Add NYT data to standard dataset to flesh out time series of deaths by county

```{r death by county}

path <- "/home/ajackson/Dropbox/Rprojects/Covid/NYTdata/covid-19-data-master/"

df <- read_csv(paste0(path, "us-counties.csv")) %>% 
  filter(state=="Texas") %>% 
  mutate(NYT_deaths=deaths, NYT_cases=cases) %>% 
  select(Date=date, County=county, NYT_deaths, NYT_cases)

foo <- readRDS("/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")

foobar <- left_join(foo, df, by=c("Date", "County"))

#foobar <- foobar %>% mutate(Deaths=pmax(Deaths, NYT_deaths,na.rm=TRUE ))
mask <- foobar$Date==ymd("2020-03-28")
foobar[mask,]$Cases <- pmax(foobar[mask,]$Cases, foobar[mask,]$NYT_cases)

foobar <- foobar %>% select(-NYT_deaths, -NYT_cases)
# Save the real file for later use
saveRDS(foobar,"/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")
# Also save to mirror site
saveRDS(foobar,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Covid.rds")
```

## Remove NYT data columns from dataset

```{r clean up NYT}

path <- "/home/ajackson/Dropbox/Rprojects/Covid/"

foo <- readRDS("/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")

foo <- foo %>% select(-NYT_deaths, -NYT_cases)
# Save the real file for later use
saveRDS(foo,"/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")
# Also save to mirror site
saveRDS(foo,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Covid.rds")
```







