---
title: "Documentation"
author: "Alan Jackson"
date: "3/22/2020"
output: html_document
---

# Documentation

The purpose of this website is to allow easy access and analysis of 
Covid-19 data for the state of Texas, including subsets by major metropolitan areas, and by individual counties. The underlying data is updated every day at 1:40 PM.

## Data

The daily data (cases by county, state totals, and Total tests) is pulled off
the website for the Texas State Department of Health 
[https://dshs.texas.gov/news/updates.shtm#coronavirus](https://dshs.texas.gov/news/updates.shtm#coronavirus).

There are a few peculiarities of this data which users should be aware of:

1. The data reported is what they had received at 8 PM the previous day
2. They update their website by noon, usually.
3. They have a category "Pending County Assignment" that can be quite large. The county assigned to a case is the county of residence, **not** the reporting county.
This has been discontinued.

For these reasons, my numbers will differ from news accounts, and tend to lag by about a day. County and metro area total will lag by several days as the state researches county of residence, but the state total should be fairly current.

On March 25, the following message appeared on the state website:

_Why did the case counts reported by DSHS increase suddenly?_

_DSHS updated the method of reporting COVID-19 cases in Texas to provide the public with more timely information. The DSHS daily case count now includes all cases reported publicly by local health departments around the state. With the change, Texas is now reporting an additional 305 cases of COVID-19._

Because the state website only gave deaths by county for a single day,
the death by county numbers are now scraped off the state emergency
response website at https://opendata.arcgis.com/datasets/bc83058386d2434ca8cf90b26dc6b580_0.csv

To infill the missing death by date by county data, the New York Times
has helpfully provided a nice datafile at https://github.com/nytimes/covid-19-data

For daily updates of the deaths by county, I use data from the Texas Division of Emergency Management website, which they get from the Health Department.

#### Changes as of mid-May:

The website for the Texas Division of Emergency Management is no longer being updated, but the state Health Department now puts data out in excel spreadsheets, so I have switched to using those.

They may be found at https://dshs.texas.gov/coronavirus/AdditionalData.aspx

Prison data is scraped from the [Texas Dept of Criminal Justice website.](https://www.tdcj.texas.gov/covid-19/offender_mac.html)


## Graph

The Graph tab is designed to allow easy data analysis to understand the time progression of the epidemic.

Epidemics grow exponentially, or not at all. The basic equation governing epidemic growth is
$$N_{d+1}=(1+Ep)N_{d}$$ where $N_{d} =$ number of people infected on day d,
$E =$ number of people an infected person exposes every day, and $p =$ the
probability that the exposure becomes an infection.

Counter measures include "social distancing", which reduces E, and hygiene
measures like hand washing, which reduces p. 

A Logistic fit starts out exponential, but then as the epidemic peaks,
it flattens and asymptotically approaches the final epidemic size.
The simple logistic equation I will use for modeling is
$$N_{d}=\frac{K}{1+e^{N_{0}+rd}}$$ where: 
* $N_{d}=$ number of cases on day d
* $K =$ final epidemic size
* $N_{0} =$ initial number of cases
* $r =$ the early growth rate (about 0.24 in China)
* $d =$ day number

A logistic has its inflection point - where it starts to flatten - at
halfway to the maximum value. So if it looks like the growth curve 
is starting to flatten, then we can expect the number of cases to
double before the epidemic ends.

### Choose the data

Data may be selected by Region (metro area or the whole state) or by individual county.

The metro areas follow the standard definition, and consist of counties:

*  Houston: Harris, Fort Bend, Galveston, Waller, Montgomery, Liberty, Brazoria, Chambers, and Austin
*  Dallas: Collin, Dallas, Denton, Ellis, Hood, Hunt, Johnson, Kaufman, Parker, Rockwall, Somervell, Tarrant and Wise
*  San Antonio: Atascosa, Bandera, Bexar, Comal, Guadalupe, Kendall, Medina, and Wilson
*  Austin: Bastrop, Caldwell, Hays, Travis, and Williamson
*  Lubbock: Crosby, Lubbock, and Lynn
*  Amarillo: Armstrong, Carson, Potter, Randall, and Oldham
*  Corpus Christi: Aransas, Nueces, and San Patricio
*  Killeen-Temple: Bell, Coryell, and Lampasas
*  Beaumont-Port Arthur: Hardin, Jefferson, and Orange

When looking at counties, I helpfully display the latest cumulative case
count for that county.

## Analysis

This tab will be devoted to various analysis tabs. 

## Cases Tab

This tab is designed to analyze aspects of the confirmed cases.

### Plotting options

Under Plotting Options are several toggles that will add things to the plot, or adjust the appearance of the plot.

#### Crowd sizes to avoid

Suppose I want there to be a less than 1% change of interacting with someone
who is infected. It is simple to calculate, it is just the number of infected
people, divided by the total population in question, times 0.01. This can
give surprisingly small numbers rather quickly, and highlights how crucial 
it is to not allow crowds of people to gather.

#### Expand scale

By default, I chop off the Y scale so that the actual data is easily seen.
The toogle will expand (or sometimes reduce) the scale so that all 
plotted objects are visible.

#### Log Scaling

The actual fit is done to the logarithm of the number of cases (as can be
seen in the displayed fit equation), because that makes the exponential a 
linear function. A key aspect of the epidemic will be to see a change in the
slope of the fit, indicating that the growth rate is slowing. That will be
easier to see on a Log plot.

### Days to Recover

Given a nominal length of infection, which seems to be around 14 days,
I estimate the number recovered, just the number of cases moved forwards
by that many days, minus the 1% who died. At the same time I subtract
the recovered from the number of cases to get an estimate of the active
cases - which is what actually matters for disease transmission.

### Data Fits

There are a variety of options to try to fit the data and thus predict
the future of the epidemic.

#### Fit Data

This option does a linear regression on $log(N) = md + b$ to find $m$ 
and $b$, the slope and intercept. The error bars derive from that fit
and represent one standard deviation. Additionally, at the bottom of the page, 
the $R^{2}$ value also derives from that fit.

#### Logistic

This option fits a logistic curve (see explanation above). The predicted
maximum number of cases and the date of the inferred inflection point
are also displayed.

#### Worldwide

The growth rate is amazingly consistent worldwide. The number I am using
comes from [dart throwing chimp](https://dartthrowingchimp.shinyapps.io/covid19-app/), and it is 
easy to see on his growth graph that most countries have followed similar 
trends. His 0.3 growth value translates to my 0.13 slope since I use log 
base 10, and he uses natural logarithms.

Because the global value is only a slope, I derive the y intercept by 
tieing the curve to the most recent datapoint.

#### User Entry

You can play with values on your own. One thing to keep an eye on as
you play with the fit, is what happens to the doubling time.

The doubling time depends only on the slope of the fit, and tells you how many
days it will take for the number of cases to double. Usually a pretty 
frightening number.

## Deaths

By default, fitting to cumulative deaths with an unweighted exponential 
function is done. The usual data selection and plot controls are provided.

A logistic fit is also provided. Note that it requires about 5 datapoints.

A tool to estimate the actual number of cases from the number of 
deaths is provided. 

CFR is the percent Case Mortality Rate, or the
mortality rate among diagnosed cases. This will, of course, be a larger
number than the IFR, or Infection Fatality Rate, which includes all
infected individuals, including those who are asymptomatic. Practically
speaking, with the poor status of testing and the rather strict criteria
being applied before allowing testing, only people who are pretty sick
are getting tested and diagnosed, so number of case estimates based on
deaths will be potentially much lower than the actual infection rate.
In any event, the literature seems to be averaging in the range of
0.7%-2.5%.

Days to Death is the average time from diagnosis to death. If only 
people who are already quite ill get tested, then the literature implies 
this number may be about 13 days. If many people who are not ill get 
tested, then this number will increase, up to perhaps 20-23 days? 

Basically I take each death, work it back to the number of cases at the
time that individual was diagnosed/tested, and multiply by the 1/CFR.

For reference, read [this paper](https://cmmid.github.io/topics/covid19/severity/global_cfr_estimates.html)

## Indicators

These are meant to be things that can indicate where a county is headed, for
good or for ill.

For cumulative cases, I fit a line in a sliding window to the cumulative case points,
and display the slope of that fit. This illustrates how the number of cases
may be growing on a day-to-day basis and should show when "the curve is
flattening". Of course the goal is for this number to go to zero.

A also provide the doubling time, measured from fitting a line in a moving
window to the logarithm of the cunmulative caseload. I like this number better, because it more sensitively demonstrates progress. I also provide a 
median smoothing filter to help clean up spikes in the data due
to reporting issues that occurred in the early days.

You can view the simple daily percent change, this is not windowed,
but is the daily percent change in number of cases.

Avg Percent Change is the daily percent change passed through a averaging
filter that is "Fit Length" long.

New Cases is just that - the daily number of new cases. The average will
help damp the noise in that measurement.

And then the same thing, as a per 100,000 population measurement, to normalize out
the county size.

If more smoothing is needed, there is a median smoothning filter that can be applied.

## Counties

In this tab we compare various measurements for all the relevant counties - 
that is - those for which there is sufficient data. By that is meant at least 10 cases, otherwise the data is really pretty useless.

Available measurements are the same as above. Averaging is done over a 5-day window.

## Regions

Here I will successively subtract metropolitan regions from the state total based on user selection. This is a convenient way to compare various regions. Again, averaging is over a 5-day window.

## Prisons

Similar to the Counties tab, but for prisons in the state. Fewer displays, to fit the
dataset for prisons.

## Map

The map is pretty simple. You can color counties by:
* total reported cases
* new cases
* active cases
* deaths
* new deaths
* deaths/case
* average percent change in case numbers, from the last 5 days
* doubling time in the last 5 days

with most measurements available as per 100,000 as well as averaged over a 5-day window.

The item, deaths divided by number of cases, should expose testing issues.
We know the mortality rate is on the order of 1%, so even allowing for 
a 2-3 week lag from infection to death, the deaths/cases should be less
than or around 1%. Really quite a bit less. 

Active cases assumes a 14 day recovery time.

You can also flag which counties contain prisons or meat-packing plants.

Note that the numbers of cases in prison are not, so far as I know, reflected in the county totals.














