---
title: "Rebuild_data"
author: "Alan Jackson"
date: "1/17/2021"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(lubridate)

knitr::opts_chunk$set(echo = TRUE)
```


## Replace Covid file from beginning with spreadsheet

```{r new file}

inpath <- "/home/ajackson/Dropbox/Rprojects/CovidTempData/TexasDataXcel/"
utpath <- "/home/ajackson/Dropbox/Rprojects/Covid/"

yesterday <- "2022-01-22"

#         get cases
df <- readxl::read_excel(paste0(inpath,"County_Case_Data_",yesterday,".xlsx"),
                         sheet="Cases by County 2020")

# No data for March 14 ---- no longer true

#lastdate <- ncol(df)-11
lastdate <- ncol(df)-13

my_colnames <- c(
                 ymd("2020-03-10"),  
                 ymd("2020-03-11"),  
                 ymd("2020-03-12"),  
                 ymd("2020-03-13"),  
                 ymd("2020-03-14"),  
                 ymd("2020-03-15")+0:lastdate)

my_colnames <- my_colnames %>% 
                 format('%Y-%m-%d')
my_colnames <- c("County", my_colnames)


#my_columns <- c(1, 7:ncol(df))
my_columns <- c(1, 6:(ncol(df)-2))

df <- df %>% 
  rename_at(my_columns,~ my_colnames)
  
df <- df[3:256,]
df <- df[-c(2:5)]
df <- df[1:(length(df)-2)]

df <- df %>%
  mutate(Match=str_to_upper(County)) %>% 
  pivot_longer(-c(County, Match), names_to="Date", values_to="Cases")

foo <- df %>% mutate(Cases=as.numeric(Cases))

####   now do 2021

#         get cases
df <- readxl::read_excel(paste0(inpath,"County_Case_Data_",yesterday,".xlsx"),
                         sheet="Cases by County 2021",
                         range=cell_rows(4:257),
                         col_names=FALSE)

lastdate <- ncol(df)-2

my_colnames <- c(ymd("2021-01-01")+0:lastdate)

my_colnames <- my_colnames %>% 
                 format('%Y-%m-%d')
my_colnames <- c("County", my_colnames)

df <- df %>% 
  rename_at(1:366,~ my_colnames)
  
df <- df %>%
  mutate(Match=str_to_upper(County)) %>% 
  pivot_longer(-c(County, Match), names_to="Date", values_to="Cases")

foo <- rbind(foo, df)

# now do 2022

#         get cases
df <- readxl::read_excel(paste0(inpath,"County_Case_Data_",yesterday,".xlsx"),
                         sheet="Cases by County 2022",
                         range=cell_rows(4:257),
                         col_names=FALSE)

lastdate <- ncol(df)-3

my_colnames <- c(ymd("2022-01-01")+0:lastdate)

my_colnames <- my_colnames %>% 
                 format('%Y-%m-%d')
my_colnames <- c("County", my_colnames)

#   Because deaths lag cases by 1 day, truncate cases so they will match up.
# The update step will fill in the missing column.

df <- df %>% 
  rename_at(1:(length(df)-1),~ my_colnames) %>% 
  select(1:(length(df)-1))
  
df <- df %>%
  mutate(Match=str_to_upper(County)) %>% 
  pivot_longer(-c(County, Match), names_to="Date", values_to="Cases")

foo <- rbind(foo, df)

######################################
# get deaths
######################################

#  2020

df <- readxl::read_excel(paste0(inpath,"Deaths_by_County_",yesterday,".xlsx"),
                         sheet="Fatalities by County 2020",
                         range=cell_rows(4:257),
                         col_names=FALSE)
lastdate <- ncol(df)-5

my_colnames <- c(ymd("2020-03-10")+0:lastdate)

my_colnames <- my_colnames %>% 
                 format('%Y-%m-%d')

my_columns <- c(1, 5:(ncol(df)))

my_colnames <- c("Match", my_colnames)


df <- df %>% 
  rename_at(my_columns,~ my_colnames)

df <- df %>% mutate_at(vars(2:ncol(df)), as.numeric) %>% 
  mutate(Match=str_to_upper(Match)) %>% 
  select(-c(2:4))

df <- df %>% pivot_longer(-Match, names_to="Date", values_to="Deaths")

df <- df %>% 
  mutate(Match=str_replace(Match, "DE WITT", "DEWITT"))

foobar <- df

#   Now 2021 ------------------

df <- readxl::read_excel(paste0(inpath,"Deaths_by_County_",yesterday,".xlsx"),
                         sheet="Fatalities by County 2021",
                         range=cell_rows(4:257),
                         col_names=FALSE)
lastdate <- ncol(df)-2

my_colnames <- c(ymd("2021-01-01")+0:lastdate)

my_colnames <- my_colnames %>% 
                 format('%Y-%m-%d')

my_colnames <- c("Match", my_colnames)

df <- df %>% 
  rename_at(1:366,~ my_colnames)

df <- df %>%
  mutate(Match=str_to_upper(Match)) %>% 
  pivot_longer(-c(Match), names_to="Date", values_to="Deaths")

df <- df %>% 
  mutate(Match=str_replace(Match, "DE WITT", "DEWITT"))

foobar <- rbind(foobar, df)

#   Now do 2022

df <- readxl::read_excel(paste0(inpath,"Deaths_by_County_",yesterday,".xlsx"),
                         sheet="Fatalities by County 2022",
                         range=cell_rows(4:257),
                         col_names=FALSE)
lastdate <- ncol(df)-2

my_colnames <- c(ymd("2022-01-01")+0:lastdate)

my_colnames <- my_colnames %>% 
                 format('%Y-%m-%d')
my_colnames <- c("Match", my_colnames)

df <- df %>% 
  rename_at(1:length(df),~ my_colnames)
  
df <- df %>%
  mutate(Match=str_to_upper(Match)) %>% 
  pivot_longer(-c(Match), names_to="Date", values_to="Deaths")

foobar <- rbind(foobar, df)

#########################################

foo <- left_join(foo, foobar, by=c("Match", "Date")) %>% 
  select(-Match)

foo$Cases <- as.numeric(foo$Cases)
foo$Deaths <- as.numeric(foo$Deaths)
foo$Date <- ymd(foo$Date)

# Save the real file for later use
saveRDS(foo,"/home/ajackson/Dropbox/Rprojects/Covid/Covid.rds")
# Also save to mirror site
saveRDS(foo,"/home/ajackson/Dropbox/mirrors/ajackson/Covid/Covid.rds")

```


```{r test tests}
#  Test new test reader

this_day <- lubridate::ymd("2022-03-08")

path <- "/home/ajackson/Dropbox/Rprojects/CovidTempData/TexasDataXcel/"

Tests_path <- paste0(path, "Tests_by_County_", this_day,".xlsx")

#  Read file into tibble

#   2020

df <- readxl::read_excel(Tests_path,
                         sheet="Total Tests 2020",
                         range=readxl::cell_rows(3:258),
                         col_names=FALSE)

my_colnames <- lubridate::ymd("2020-09-13")+0:(ncol(df)-2)
my_colnames <- my_colnames %>% 
  format('%Y-%m-%d')
my_colnames <- c("County", my_colnames)
my_columns <- c(1:ncol(df))

df <- df %>% 
  rename_at(my_columns,~ my_colnames)

df <- df %>% pivot_longer(-County, names_to="Date", values_to="Tests")

df <- df %>% mutate(Tests=as.numeric(Tests))
df <- df %>% mutate(Date=lubridate::as_date(Date))

#   2021

df2 <- readxl::read_excel(Tests_path,
                         sheet="Total Tests 2021",
                         range=readxl::cell_rows(3:258),
                         col_names=FALSE)

my_colnames <- lubridate::ymd("2021-01-01")+0:(ncol(df2)-2)
my_colnames <- my_colnames %>% 
  format('%Y-%m-%d')
my_colnames <- c("County", my_colnames)
my_columns <- c(1:ncol(df2))

df2 <- df2 %>% 
  rename_at(my_columns,~ my_colnames)

df2 <- df2 %>% pivot_longer(-County, names_to="Date", values_to="Tests")

df2 <- df2 %>% mutate(Tests=as.numeric(Tests))
df2 <- df2 %>% mutate(Date=lubridate::as_date(Date))

#   Merge the two after some cleanup

df <- rbind(df, df2)

#   2022

df2 <- readxl::read_excel(Tests_path,
                         sheet="Total Tests 2022",
                         range=readxl::cell_rows(3:258),
                         col_names=FALSE)

my_colnames <- lubridate::ymd("2022-01-01")+0:(ncol(df2)-2)
my_colnames <- my_colnames %>% 
  format('%Y-%m-%d')
my_colnames <- c("County", my_colnames)
my_columns <- c(1:ncol(df2))

df2 <- df2 %>% 
  rename_at(my_columns,~ my_colnames)

df2 <- df2 %>% pivot_longer(-County, names_to="Date", values_to="Tests")

df2 <- df2 %>% mutate(Tests=as.numeric(Tests))
df2 <- df2 %>% mutate(Date=lubridate::as_date(Date))

#   Merge the two after some cleanup

df <- rbind(df, df2)

total_tests <- last(df$Tests[df$County=="Total"])


```

