---
title: "Shiny Analytics Testbed"
author: "Alan Jackson"
date: "4/1/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(leaflet)
library(leafpop) # for popup on map
library(ggplot2)
library(ggrepel)
library(stringr)
library(lubridate)

knitr::opts_chunk$set(echo = TRUE)
```

## Shiny Analytics Testbed

Mirror the entire analytic portion of the shiny app here where testing and debugging
is much easier.

```{r Initialization}
###################################
#   get and set up the basic data
###################################

#   Directory where data is stored

DataLocation <- "https://www.ajackson.org/Covid/"
DataArchive <- "https://www.ajackson.org/SharedData/"

#   Tibble database

#   Case data
z <- gzcon(url(paste0(DataLocation, "Covid.rds")))
DF <- readRDS(z)
close(z)
#   Testing data
z <- gzcon(url(paste0(DataLocation, "Testing.rds")))
TestingData <- readRDS(z)
close(z)
TestingData$Total <- as.numeric(TestingData$Total)
#   Death data
z <- gzcon(url(paste0(DataLocation, "Deaths.rds")))
DeathData <- readRDS(z)
close(z)

#   County polygons
Texas <- readRDS(gzcon(url(paste0(DataArchive, "Texas_County_Outlines_lowres.rds"))))


init_zoom <<- 6
MapCenter <<- c(-99.9018, 31.9686) # center of state

global_slope <<- 0.13
# https://dartthrowingchimp.shinyapps.io/covid19-app/

# Clean up footnotes

DF$County <- str_replace(DF$County, "\\d", "")

# drop rows with zero cases

DF <- DF %>% filter(Cases>0)

# Add Statewide Totals per day

DF <- DF %>% select(-LastUpdate) %>% bind_rows(
                  DF %>%
                  group_by(Date) %>% 
                  summarise(Cases = sum(Cases), Deaths=sum(Deaths)) %>% 
                  mutate(County="Total")
                 ) %>% 
    arrange(Date)

# Calc days since March 10

DF <- DF %>% 
    mutate(Days=as.integer(Date-ymd("2020-03-10")))

DeathData <<- DeathData %>% 
    mutate(Days=as.integer(Date-ymd("2020-03-10")))

# Fix Deaths field

DF$Deaths <- str_replace(DF$Deaths,"-", "na")

DF <- DF %>% 
  mutate(Deaths=as.numeric(Deaths)) %>% 
  mutate(Deaths=na_if(Deaths, 0))


# Add dummy Estimate field

DF <<- DF %>% 
    mutate(Estimate=Cases)


#   Last date in dataset formatted for plotting

sf <<- stamp_date("Sunday, Jan 17, 1999")
lastdate <<- sf(DF$Date[nrow(DF)])

LastDate <<- DF[nrow(DF),]$Date


# Load population of counties into tibble
Counties <<- tribble(
    ~County, ~Population,
    "Harris", 4602523, "Dallas", 2586552, "Tarrant", 2019977,
    "Bexar", 1925865, "Travis", 1203166, "Collin", 944350, "Hidalgo", 849389,
    "El Paso", 837654, "Denton", 807047, "Fort Bend", 739342,
    "Montgomery", 554445, "Williamson", 527057, "Cameron", 421750,
    "Nueces", 360486, "Brazoria", 353999, "Bell", 342236,
    "Galveston", 327089, "Lubbock", 301454, "Webb", 272053,
    "Jefferson", 255210, "McLennan", 248429, "Smith", 225015,
    "Brazos", 219193, "Hays", 204150, "Ellis", 168838,
    "Midland", 164194, "Johnson", 163475, "Ector", 158342,
    "Guadalupe", 155137, "Taylor", 136348, "Comal", 135097,
    "Randall", 132475, "Wichita", 131818, "Parker", 129802,
    "Grayson", 128560, "Gregg", 123494, "Potter", 120899,
    "Kaufman", 118910, "Tom Green", 117466, "Bowie", 93858,
    "Rockwall", 93642, "Hunt", 92152, "Victoria", 91970,
    "Angelina", 87607, "Orange", 84047, "Bastrop", 82577,
    "Liberty", 81862, "Henderson", 80460, "Coryell", 75389,
    "Walker", 71539, "San Patricio", 67046, "Harrison", 66645,
    "Nacogdoches", 65558, "Wise", 64639, "Starr", 63894,
    "Maverick", 57970, "Anderson", 57863, "Hood", 56901,
    "Hardin", 56379, "Van Zandt", 54368, "Rusk", 53595,
    "Cherokee", 51903, "Kerr", 51365, "Waller", 49987,
    "Lamar", 49532, "Medina", 49334, "Val Verde", 49027,
    "Atascosa", 48828, "Navarro", 48583, "Wilson", 48198,
    "Polk", 47837, "Burnet", 45750, "Wood", 43815,
    "Kendall", 41982, "Wharton", 41551, "Erath", 41482,
    "Caldwell", 41401, "Jim Wells", 41192, "Upshur", 40769,
    "Chambers", 40292, "Cooke", 39571, "Brown", 37834,
    "Matagorda", 36743, "Howard", 36667, "Hopkins", 36240,
    "Jasper", 35504, "Hill", 35399, "Washington", 34796,
    "Fannin", 34175, "Hale", 34113, "Titus", 32730,
    "Bee", 32691, "Kleberg", 31425, "Cass", 30087,
    "Austin", 29565, "Palo Pinto", 28317, "San Jacinto", 27819,
    "Grimes", 27630, "Uvalde", 27009, "Gillespie", 26208,
    "Shelby", 25478, "Fayette", 25066, "Aransas", 24763,
    "Milam", 24664, "Limestone", 23515, "Panola", 23440,
    "Hockley", 23162, "Houston", 22955, "Gray", 22685,
    "Calhoun", 21807, "Moore", 21801, "Bandera", 21763,
    "Willacy", 21754, "Hutchinson", 21571, "Tyler", 21496,
    "Colorado", 21022, "Gonzales", 20667, "Lampasas and Llano", 20640,
    "DeWitt", 20435, "Gaines", 20321, "Lavaca", 19941,
    "Jones", 19891, "Freestone", 19709, "Montague", 19409,
    "Frio", 19394, "Deaf Smith", 18899, "Eastland", 18270,
    "Bosque", 18122, "Young", 18114, "Burleson", 17863,
    "Andrews", 17818, "Falls", 17299, "Scurry", 17239,
    "Leon", 17098, "Lee", 16952, "Robertson", 16890,
    "Pecos", 15797, "Karnes", 15387, "Reeves", 15125,
    "Nolan", 14966, "Jackson", 14820, "Trinity", 14569,
    "Zapata", 14369, "Madison", 14128, "Newton", 14057,
    "Callahan", 13770, "Comanche", 13495, "Lamb", 13262,
    "Dawson", 12964, "Wilbarger", 12906, "Camp", 12813,
    "Terry", 12615, "Morris", 12424, "Red River", 12275,
    "Zavala", 12131, "Live Oak", 12123, "Ward", 11586,
    "Rains", 11473, "Duval", 11355, "Blanco", 11279,
    "Franklin", 10679, "Dimmit", 10663, "Sabine", 10458,
    "Clay", 10387, "Ochiltree", 10348, "Runnels", 10310,
    "Marion", 10083, "Parmer", 9852, "Stephens", 9372,
    "Brewster", 9216, "Jack", 8842, "Archer", 8789,
    "Somervell", 8743, "Yoakum", 8571, "Mitchell", 8558,
    "Coleman", 8391, "San Augustine", 8327, "Hamilton", 8269,
    "McCulloch", 8098, "Winkler", 7802, "Castro", 7787,
    "Goliad", 7531, "Swisher", 7484, "La Salle", 7409,
    "Dallam", 7243, "Refugio", 7236, "Childress", 7226,
    "Brooks", 7180, "Presidio", 7123, "Bailey", 7092,
    "Garza", 6288, "Carson", 6032, "San Saba", 5962,
    "Floyd", 5872, "Crosby", 5861, "Haskell", 5809,
    "Lynn", 5808, "Hartley", 5767, "Martin", 5614,
    "Hansford", 5547, "Wheeler", 5482, "Jim Hogg", 5282,
    "Delta", 5215, "Mills", 4902, "Crane", 4839,
    "Kimble", 4408, "Concho", 4233, "Mason", 4161,
    "Hudspeth", 4098, "Hemphill", 4061, "Hardeman", 3952,
    "Fisher", 3883, "Sutton", 3865, "Reagan", 3752,
    "Knox", 3733, "Kinney", 3675, "Upton", 3634,
    "Crockett", 3633, "Baylor", 3591, "Lipscomb", 3469,
    "Real", 3389, "Donley", 3387, "Shackelford", 3311,
    "Coke", 3275, "Hall", 3074, "Schleicher", 3061,
    "Sherman", 3058, "Collingsworth", 2996, "Cochran", 2904,
    "Culberson", 2241, "Jeff Davis", 2234, "Dickens", 2216,
    "Menard", 2123, "Oldham", 2090, "Edwards", 2055,
    "Armstrong", 1916, "Cottle", 1623, "Throckmorton", 1567,
    "Briscoe", 1546, "Irion", 1524, "Glasscock", 1430,
    "Foard", 1408, "Stonewall", 1385, "Motley", 1156,
    "Sterling", 1141, "Roberts", 885, "Terrell", 862,
    "Kent", 749, "Borden", 665, "McMullen", 662,
    "Kenedy", 595, "King", 228, "Loving", 102
)

#   Sort counties with 20 largest first, then alphabetical

ByPop <- arrange(Counties, -Population)
ByAlpha <- arrange(ByPop[21:nrow(ByPop),], County)
Counties <- bind_rows(ByPop[1:20,], ByAlpha)
ByPop <- ByAlpha <- NULL

Regions <<- tribble(
            ~Region, ~Population, ~Label,
            "Texas", 27864555, "Texas",
            "Houston-Galv", 6779104, "Houston/Galveston Metro Region",
            "Dallas-Fort Worth", 4938225, "Dallas/Fort Worth Metro Region",
            "San Antonio", 2426204, "San Antonio Metro Region",
            "Austin", 2058351, "Austin Metro Region")

DefineRegions <<- tribble(
    ~Region, ~List,
    "Texas", c("Total"),
    "Houston-Galv", c("Harris", "Fort Bend", "Galveston", "Waller", "Montgomery", "Liberty", "Brazoria", "Chambers", "Austin"),
    "Dallas-Fort Worth", c("Collin", "Dallas", "Denton", "Ellis", "Hood", "Hunt", "Johnson", "Kaufman", "Parker", "Rockwall", "Somervell", "Tarrant", "Wise"),
    "San Antonio", c("Atascosa", "Bandera", "Bexar", "Comal", "Guadalupe", "Kendall", "Medina", "Wilson"), 
    "Austin", c("Bastrop", "Caldwell", "Hays", "Travis", "Williamson")
)

# https://docs.google.com/document/d/1ETeXAfYOvArfLvlxExE0_xrO5M4ITC0_Am38CRusCko/edit#
Disease <- tibble::tribble(
              ~Demographics, "% Hosp", "% Hosp ICU", "% CFR",
                      "12%", "0-9", "0.1%", "5.0%", "0.002%",
                      "13%", "10-19", "0.3%", "5.0%", "0.006%",
                      "14%", "20-29", "1.2%", "5.0%", "0.03%",
                      "13%", "30-39", "3.2%", "5.0%", "0.08%",
                      "12%", "40-49", "4.9%", "6.3%", "0.15%",
                      "13%", "50-59", "10.2%", "12.2%", "0.60%",
                      "11%", "60-69", "16.6%", "27.4%", "2.20%",
                       "7%", "70-79", "24.3%", "43.2%", "5.10%",
                       "4%", "80+", "27.3%", "70.9%", "9.30%"
                            )

# prep mapping polygons

TodayData <<- DF %>% filter(Date==LastDate) %>% 
  filter(County!="Pending County Assignment") %>% 
  left_join(., Counties, by="County") %>% 
  mutate(percapita=Cases/Population*100000)

MappingData <<-  merge(Texas, TodayData,
                      by.x = c("County"), by.y = c("County"),
                      all.x = TRUE) 

# Build labels for map

MappingData <<- MappingData %>%
  mutate(percapita=signif(percapita,3)) %>% 
  mutate(Deaths=na_if(Deaths, 0)) %>% 
  mutate(DPerC=na_if(signif(Deaths/Cases,2),0))

MapLabels <<- lapply(seq(nrow(MappingData)), function(i) {
  htmltools::HTML(
    str_replace_all(
      paste0( MappingData[i,]$County, ' County<br>', 
              MappingData[i,]$Cases,' Cases Total<br>', 
              MappingData[i,]$percapita, " per 100,000<br>",
              MappingData[i,]$Deaths, " Deaths<br>",
              MappingData[i,]$DPerC, " Deaths per Case"),
      "NA", "Zero"))
})

span <- function(vector){
  foo <- range(vector, na.rm=TRUE)
  return(max(foo) - min(foo))
}

```

## Emulate the GUI by setting the varibles manually

```{r gui}

#####   Graph Tab

## Data select

input <- tibble(dataset="Region", # Region or county
                region="Texas",
                county="Hidalgo")

##  Fitting
input <- input %>% add_column(
                modeling="do fit", # do fit, standard, user
                fit=global_slope,
                intercept=1.00,
                weights=TRUE)
##  Plot controls
input <- input %>% add_column(
                logscale=FALSE,
                zoom=FALSE,
                mult=FALSE,
                mult_pos=2,
                estmiss=FALSE,
                avoid=FALSE
                )

```

##  A few helper routines that shiny uses

```{r helpers}

showNotification <- function(foo) {
  print(foo)
}


```


##  Prep data

```{r prepdata}
  #---------------------------------------------------    
  #------------------- Prep Data ---------------------
  #---------------------------------------------------    
  prep_data <- function(DF=DF,
                        in_dataset="Region", 
                        in_area="Texas"
                        ) { 
    # return population, label for graph title and tibble subset
    print(":::::::  prep_data")
    if (in_dataset=="Region") { # work with regions
        print(paste("prep_data - 1", DefineRegions$List[DefineRegions$Region==in_area]))######################### print
      PopLabel <- Regions %>% filter(Region==in_area)
      target <- unlist(DefineRegions$List[DefineRegions$Region==in_area])
      subdata <- DF %>% 
          filter(County %in% target) %>% 
          group_by(Date) %>% 
          summarise(Cases=sum(Cases), Days=mean(Days), Estimate=sum(Estimate))
print(paste("prep_data - 2", in_area))######################### print
print(subdata)
      return(c(subdata, PopLabel))
    } else { # select a county
print(paste("prep_data - 3", in_area))######################### print
      #   Is there any data?
      if (! in_area %in% DF$County) {
        showNotification(paste("No reported cases in", in_area))
        return()
      }
      
      PopLabel <- Counties %>% filter(County==in_area) %>% 
                     mutate(Label=paste(in_area, "County"))
      subdata <- DF %>% filter(County==in_area)
print(subdata)
      return(c(subdata, PopLabel))
    }
  } # end prep_data

######################################################################
#           Test Section
######################################################################

prep_data(DF, 'Region', 'Texas')
prep_data(DF, 'county', 'Hidalgo')

```

## Various routines

```{r routines}
  #---------------------------------------------------    
  #-----------Build an exponential model -------------
  #---------------------------------------------------    
  build_expmodel <- function(data, 
                             indep="Cases", # independent variable
                             in_weights, 
                             fit=c('all', 'none', "b_only", "m_only"),
                             m=1.3,
                             b=1){
    print(":::::::  build_expmodel")
      #   Go 10 days into future
      begin <- data$Date[1] # date of first reported case
      LastDate <<- data[nrow(data),]$Date
      lastday <- as.integer(LastDate - begin) + 1 # last day of real data
      dayseq <- 0:(lastday + 9)
      dateseq <- as_date(begin:(LastDate+10))
      x <- data$Days
      x <- 0:(lastday-1)
      y <- data[,indep][[1]]
      if (in_weights) {
        weights <- (1:nrow(subdata))**2.5
      } else {
        weights <- replicate(nrow(subdata), 1)
      }
      print(data)
      my_data <- tibble(x=x, y=y, weights=weights)
      print("indep, x, y, my_data")
      print(indep)
      print(x)
      print(y)
      print(my_data)
        
      if (fit=="all") { 
        model <- lm(log10(y)~x, data=my_data, weights=weights)
        m <- model[["coefficients"]][["x"]]
        b <- model[["coefficients"]][["(Intercept)"]]
        Rsqr <- summary(model)$adj.r.squared
        std_dev <- sigma(model)
      } else if (fit=="none") {
        m <- m
        b <- b
        Rsqr <- 1
        std_dev <- 0
      } else if (fit=="b_only") {
        #model <- lm(log10(y)-m*x~1, weights=weights)
        #m <- model[["coefficients"]][["x"]]
        #b <- model[["coefficients"]][["(Intercept)"]]
        b <- log10(data$Cases[lastday]) - m*(lastday-1)
        #Rsqr <- summary(model)$adj.r.squared
        #std_dev <- sigma(model)
        Rsqr <- 1
        std_dev <- 0
        print(paste("----build_expline-2--", model))
      } else if (fit=="m_only") {
        model <- lm(I(x - b) ~ 0 + log10(y), weights=weights)
        m <- model[["coefficients"]][["x"]]
        b <- model[["coefficients"]][["(Intercept)"]]
        Rsqr <- summary(model)$adj.r.squared
        std_dev <- sigma(model)
        print(paste("----build_expline-3--", model))
      }
  
      print(paste("m and b",m,b))
      Cases <- 10**(m*dayseq+b)
      print(Cases)
      SD_upper <- Cases+Cases*std_dev
      SD_lower <- Cases-Cases*std_dev
      
      ExpLine <- tibble( Days=dayseq, Date=dateseq,!!indep:=Cases,
                         SD_upper=SD_upper, SD_lower=SD_lower) 
      print(paste("--5--"))######################### print
      print(ExpLine)######################### print
      #  return a tibble
      tribble(~Line, ~m, ~b, ~Rsqr,
               ExpLine, m, b, Rsqr)
  }  



  #---------------------------------------------------    
  #------------------- Build Legend ------------------
  #---------------------------------------------------    
  
  build_legend <- function(p, title, plabs, pvals, pbrks){
    print(":::::::  build_legend")
    
    #   Create list of named characters
    names(pvals) <- pbrks
    
    legend <- theme(legend.position=c( 0.12, 0.5 ))
      
    Legend_layer <- scale_color_manual(name = title, 
                                         values = pvals,
                                         labels = plabs,
                                         breaks = pbrks)
    p <- p + legend + Legend_layer 
    
    return(p)
  }

######################################################################
#           Test Section
######################################################################


foo <- build_expmodel(subdata,
                      indep="Cases",
                      in_weights=input$weights,
                      fit="all")
```


## Basic Plot

```{r basic plot}

  #---------------------------------------------------    
  #------------------- Build Basic Plot --------------
  #---------------------------------------------------    
  
  build_basic_plot <- function(subdata,
                               TestingData,
                               in_modeling=c("do fit", "standard", "user"), 
                               in_fit,
                               in_intercept,
                               in_weights,
                               in_logscale,
                               in_zoom,
                               in_mult,
                               in_mult_pos,
                               in_estmiss,
                               in_avoid
    ){
    print(":::::::  build_basic_plot")

    begin <- subdata$Date[1] # date of first reported case
    
    # Build an exponential model
    if (in_modeling == "do fit") { # full fit
      foo <- build_expmodel(subdata,
                            indep="Cases",
                            in_weights=in_weights,
                            fit="all")
    } else if (in_modeling == "standard") { # global standard
      foo <- build_expmodel(subdata,
                            indep="Cases",
                            in_weights=in_weights,
                            fit="b_only",
                            m=global_slope)
    } else { # user
      foo <- build_expmodel(subdata,
                            indep="Cases",
                            in_weights=in_weights,
                            fit="none",
                            m=in_fit,
                            b=in_intercept)
    }
      print("build_basic_plot ---- 1")
    EqText <- paste0("Fit is log(Cases) = ",
                     signif(foo$m,3),"*Days + ",
                     signif(foo$b,3))
    ExpLine <- foo$Line[[1]]
    print("ExpLine")
    print(ExpLine)
    xform <- 2*signif(max(TestingData$Total)/(6*max(subdata$Cases)),2)
      print("build_basic_plot ---- 2")
 
    #  Basic canvas     
    p <- subdata %>% 
          ggplot(aes(x=Date, y=Cases))
    #  Plot Exponential fit line, Extension of line, and testing data
    p <-  p +
          expand_limits(x = LastDate+10) +
          geom_line(data=ExpLine,
                    aes(x=Date, y=Cases,
                        color="fit"),
                    size=1,
                    linetype="dashed") +
          geom_line(data=ExpLine[1:(nrow(ExpLine)-10),],
                    aes(x=Date, y=Cases,
                        color="fit" ),
                    size=1,
                    linetype="solid") +
          geom_point(data=ExpLine[(nrow(ExpLine)-9):nrow(ExpLine),],
                        aes(x=Date, y=Cases),
                     shape=20, size=2, fill="blue") +
          geom_point(data=TestingData,
                        aes(x=Date, y=Total/xform, color="tests"),
                     size=3, shape=23, fill="black") +
          geom_text(data=TestingData,
                    aes(x=Date, y=Total/xform, label=Total),
                    nudge_x=-1.00, nudge_y=0.0) +
          theme(text = element_text(size=20)) +
          labs(title=paste0("COVID-19 Cases in ",PopLabel$Label), 
               subtitle=paste0(" as of ", lastdate))
          
    if (!in_logscale) {
        p <- p + geom_col(alpha = 2/3)  +
             geom_label(aes(label=Cases), 
                            stat='identity',
                            size = 3) 
     } else {
        
        p <- p + geom_point(aes(color="data"), size=2) +
                 geom_text(aes(label=Cases),
                           nudge_x=-0.50, nudge_y=0.0)
     }       

      print("build_basic_plot ---- 3")
      if (!is.nan(ExpLine$SD_lower[1]) & in_modeling=="do fit"){
           p <- p + geom_errorbar(data=ExpLine[(nrow(ExpLine)-9):nrow(ExpLine),],
                        aes(x=Date, y=Cases, ymin=SD_lower, ymax=SD_upper)) 
      }
      print("build_basic_plot ---- 4")
      
      if (in_logscale) {
        trans_value <- "log10"
        min_limit <- min(subdata$Cases[1], 10)
      } else {
        trans_value <- "identity"
        min_limit <- 0
      }
      print("build_basic_plot ---- 5")
      if (!in_zoom) {
          # limit height of modeled fit
        p <- p + scale_y_continuous(limits=c(min_limit, 6*max(subdata$Cases)),
                                    sec.axis = sec_axis(~.*xform, 
                                    name = "Statewide Test Total"),
                                    trans=trans_value)
      } else {
        p <- p + scale_y_continuous(limits=c(min_limit, max(ExpLine$Cases)),
                                    sec.axis = sec_axis(~.*xform, 
                                    name = "Statewide Test Total"),
                                    trans=trans_value)
      }
      print("build_basic_plot ---- 6")
      leg_labs <- c("Data", "Fit", "Tests") # Labels for legend
      leg_vals <- c("black", "blue", "black") # Color values
      leg_brks <- c("data", "fit", "tests") # Breaks (named lists)
      if (in_mult) {
          p <- add_mult(p, in_mult_pos=in_mult_pos, in_weights = in_weights)
          leg_labs <- c(leg_labs, "Multiplied")
          leg_vals <- c(leg_vals, "red")
          leg_brks <- c(leg_brks, "mult")
      } 
      print("build_basic_plot ---- 7")
      if (in_estmiss) {
          p <- add_estmiss(p)
          leg_labs <- c(leg_labs, "Missed\nCases")
          leg_vals <- c(leg_vals, "green")
          leg_brks <- c(leg_brks, "est_miss")
      } 
      print("build_basic_plot ---- 8")
      if (in_avoid) {
        if (in_logscale) {
          showNotification("Crowdsize not available with log scale")
        } else {
          p <- add_crowdsize(p, in_mult, in_mult_pos, in_weights)
        }
      }
      print("build_basic_plot ---- 9")
      p <-  build_legend(p, "Cases",
                             leg_labs, # Labels for legend
                             leg_vals, # Color values
                             leg_brks # Breaks (named lists)
      )
      m <- foo$m
      b <- foo$b 
      Rsqr <- foo$Rsqr
      #output$data_details <- data_details(subdata,
      #                                     "Cases",
      #                                     EqText,
      #                                     m,
      #                                     b,
      #                                     Rsqr)
      
    return(p)
  }


######################################################################
#           Test Section
######################################################################
input$logscale <- TRUE
input$weights <- TRUE
      p <- build_basic_plot(subdata,
                            TestingData,
                            input$modeling,
                            input$fit,
                            input$intercept,
                            input$weights,
                            input$logscale,
                            input$zoom,
                            input$mult,
                            input$mult_pos,
                            input$estmiss,
                            input$avoid)

      
          print(p)
```








